name: Deploy docker
on:
  [workflow_dispatch]

jobs:
  deploy:
    name: deploy image
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.SSH_HOST }} > ~/.ssh/known_hosts
      - name: create .env
        run: |
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "cd /usr/test && \\
            rm -f .env && \\
            sudo touch .env && \\
            sudo echo MONGO_DB_URI=${{ secrets.MONGO_URI }} > .env && \\
            sudo echo MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }} > .env && \\
            sudo echo OPEN_AQ_API_KEY=${{ secrets.OPENAQ_KEY }} > .env && \\
            sudo echo CDSAPI_URL=${{ secrets.CDSAPI_URL }} > .env && \\
            sudo echo CDSAPI_KEY=${{ secrets.CDSAPI_KEY }} > .env && \\
            sudo cat .env" && \\
            exit"
      - name: activate docker
        run: |  
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "sudo docker run -d -t ghcr.io/${{ github.repository }}/test:latest && exit"
      - name: clean up
        run: |
          exit
          rm -rf ~/.ssh

