name: Publish ETL docker image
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN}} ghcr.io
      - name: build
        run: |
          docker build . -t ghcr.io/${{ github.repository }}/test:latest -f Dockerfile.prod
      - name: publish
        run: |
          docker push ghcr.io/${{ github.repository }}/test:latest