name: Publish ETL docker image
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN}} ghcr.io
      - name: build
        run: |
          docker build . -t ghcr.io/${GITHUB_REPOSITORY@L}/folder/test2:latest -f Dockerfile.prod
      - name: publish
        run: |
          docker push ghcr.io/${GITHUB_REPOSITORY@L}/folder/test2:latest
