name: Publish ETL docker image
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: lowercase
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
      - name: write it
        run: |
          echo "The value of REPO is ${REPO}"
      - name: login
        run: |
          echo ${{ secrets.GITHUB_TOKEN}} | docker login --username ${{ github.actor }} --password-stdin ghcr.io
      - name: build
        run: |
          docker build . -t ghcr.io/${REPO}/folder/test2:latest -f Dockerfile.prod
      - name: publish
        run: |
          docker push ghcr.io/${REPO}/folder/test2:latest
